version: '2'

services:
  php:
    build:
      context: php7.2-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${APP_PATH}:/var/www/web
    networks:
      shent:
        ipv4_address: 172.16.238.2
        ipv6_address: 2001:3984:3989::2
    container_name: php

  nginx:
    build: nginx
    ports:
      - 8002:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - php
    container_name: nginx
    networks:
      shent:
        ipv4_address: 172.16.238.1
        ipv6_address: 2001:3984:3989::1

networks:
  shent:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
